# Generated by Django 4.1.7 on 2023-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not considered'), (1, 'Accept'), (2, 'Reject')], default=0, verbose_name='Status response'),
        ),
    ]
